DiscussProject/Models/Article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace DiscussProject.Models
{
    public class Article
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime CreateTime { get; set; }
        public string Content { get; set; }
        public int Like { get; set; }
        public int ViewNum { get; set; }
        public string Category { get; set; }
        public ICollection<Comment> Comments { get; set; }
        public virtual int UserId { get; set; }
        [ForeignKey("UserId")]
        public User Author { get; set; }
    }
    public class ArticleContext : DbContext
    {
        public ArticleContext() : base("name=DiscussProject")
        {

        }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}

DiscussProject/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DiscussProject.Models;
using System.Linq.Expressions;

namespace DiscussProject.Controllers
{
    public class ArticlesController : Controller
    {
        private ArticleContext db = new ArticleContext();
        private UserContext userdb = new UserContext();

        // GET: Articles
        public ActionResult Index()
        {
            return View(db.Articles.ToList());
        }

        // GET: Articles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Articles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Articles/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,CreateTime,Content,Like,ViewNum,Category")] Article article)
        {
            

            if (ModelState.IsValid)
            {
                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index2");
            }

            return View(article);
        }

        public ActionResult Create2()
        {
            List<SelectListItem> itemlist = new List<SelectListItem>();
            itemlist.Add(new SelectListItem() { Value = "分享", Text = "分享" });
            itemlist.Add(new SelectListItem() { Value = "讨论", Text = "讨论" });
            itemlist.Add(new SelectListItem() { Value = "学术", Text = "学术" });
            itemlist.Add(new SelectListItem() { Value = "娱乐", Text = "娱乐" });
            itemlist.Add(new SelectListItem() { Value = "交友", Text = "交友" });
            SelectList select = new SelectList(itemlist, "Value", "Text", "分享");
            ViewBag.select = select;
            return View();
        }

        //POST: Articles/Create
        //为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        //更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create2([Bind(Include = "Title,Content,Category")] Article article)
        {
            article.Author= db.Users.Find((int)Session["Id"]);
            article.CreateTime = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index2");
            }

            return View(article);
        }

        // GET: Articles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        public ActionResult Edit2(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            List<SelectListItem> itemlist = new List<SelectListItem>();

            itemlist.Add(new SelectListItem() { Value = "分享", Text = "分享" });
            itemlist.Add(new SelectListItem() { Value = "讨论", Text = "讨论" });
            itemlist.Add(new SelectListItem() { Value = "学术", Text = "学术" });
            itemlist.Add(new SelectListItem() { Value = "娱乐", Text = "娱乐" });
            itemlist.Add(new SelectListItem() { Value = "交友", Text = "交友" });
            SelectList select = new SelectList(itemlist, "Value", "Text", article.Category);
            ViewBag.select = select;
            ViewBag.content = article.Content;
            return View(article);
        }

        // POST: Articles/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Title,Content,Category")] Article article)
        {
            article.Author = db.Users.Find((int)Session["Id"]);
            article.CreateTime = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Entry(article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit2([Bind(Include = "Id,Title,Content,Category")] Article article)
        {

            article.UserId = (int)Session["Id"];
            article.CreateTime = DateTime.Now;
                if (ModelState.IsValid)
                {
                    db.Entry(article).State = EntityState.Modified;
                    db.SaveChanges();
                    return Redirect("/Articles/Detail2?id="+article.Id);
                }
            return View(article);
        }

        // GET: Articles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Article article = db.Articles.Find(id);
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ViewResult Index2()
        {
            int id = (int)Session["id"];
            ViewBag.User = db.Users.Find(id);
            return View(db.Articles.ToList());
        }
        public ActionResult Detail2(int id)
        {
            int uid = (int)Session["id"];
            ViewBag.myinfo = db.Users.Find(uid);
            var model = db.Articles.Find(id);
            model.Author = db.Users.Find(model.UserId);
            var comments =  from item in db.Comments where model.Id.Equals(item.Post.Id) select item;
            var tmp_com = comments.ToList();
            for (int i = 0; i < tmp_com.Count; i++)
            {
                tmp_com[i].User = db.Users.Find(tmp_com[i].UserId);
            }
            ViewData["comments"] = tmp_com;
            return View(model);
        }
        public JsonResult FindByCategory(string category)
        {
            var result = from item in db.Articles where item.Category.Equals(category) select item;
            var tmp = result.ToArray();
            for (int i = 0; i < tmp.Length; i++)
            {
                var author = db.Users.Find(tmp[i].UserId);
                tmp[i].Author = author;
            }
            return Json(tmp, JsonRequestBehavior.AllowGet);
        }
        public JsonResult FindByTitleLike(string title)
        {
            var result =  from item in db.Articles where item.Title.Contains(title) select item;
            var tmp = result.ToArray();
            for (int i = 0; i < tmp.Length; i++)
            {
                var author = db.Users.Find(tmp[i].UserId);
                tmp[i].Author = author;
            }
            return Json(tmp, JsonRequestBehavior.AllowGet);
        }
        public JsonResult FindALL()
        {
            var datas = db.Articles;
            foreach (var item in datas)
            {
                item.Author = db.Users.Find(item.UserId);

            }
            return Json(datas, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SubmitComment(FormCollection collection)
        {
            Comment data = new Comment();
            data.Content = Request.Form["content"];
            data.CreateTime = DateTime.Now;
            data.Post = db.Articles.Find(Convert.ToInt32(Request.Form["articleId"]));
            User user = db.Users.Find((int)Session["Id"]);
            data.User = user;
            db.Comments.Add(data);
            db.SaveChanges();
            return Redirect("/Articles/Detail2?id=" + Request.Form["articleId"]);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DiscussProject/Views/Articles/Create.cshtml
@model DiscussProject.Models.Article

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Like, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Like, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Like, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ViewNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ViewNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DiscussProject/Views/Articles/Create2.cshtml
@model DiscussProject.Models.Article

@{
    ViewBag.Title = "Create2";
    Layout = "~/Views/Shared/_ArticleLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="layui-container fly-marginTop">
        <div class="fly-panel" pad20 style="padding-top: 5px;">
            <!--<div class="fly-none">没有权限</div>-->
            <div class="layui-form layui-form-pane">
                <div class="layui-tab layui-tab-brief" lay-filter="user">
                    <ul class="layui-tab-title">
                        <li class="layui-this">发表新帖<!-- 编辑帖子 --></li>
                    </ul>
                    <div class="layui-form layui-tab-content" id="LAY_ucm" style="padding: 20px 0;">
                        <div class="layui-tab-item layui-show">
                            <form action="" method="post">
                                <div class="layui-row layui-col-space15 layui-form-item">
                                    <div class="layui-col-md3">
                                        <label class="layui-form-label">所在专栏</label>

                                        <div class="layui-unselect layui-form-select">
                                            <div class="layui-input-block">
                                                @*@Html.DropDownList("Category",(SelectList)ViewBag.aaa);*@
                                                @Html.DropDownListFor(model => model.Category, ViewBag.select as SelectList, new { @class = "form-control", @name = "class" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="layui-col-md9">
                                        <label for="L_title" class="layui-form-label">标题</label>
                                        

                                        <div class="layui-input-block">
                                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @type = "text", @class = "layui-input", @id = "L_title", @name = "title", @autocomplete = "off" } })
                                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                            <!-- <input type="hidden" name="id" value="{{d.edit.id}}"> -->
                                        </div>
                                    </div>
                                </div>
                                <div class="layui-form-item layui-form-text">
                                    <div class="layui-input-block">
                                        @*<textarea id="L_content" name="content" required lay-verify="required" placeholder="详细描述" class="layui-textarea fly-editor" style="height: 260px;"></textarea>*@
                                        @*@Html.TextArea("content","", new { htmlAttributes = new { @type = "textarea", @class = "layui-textarea fly-editor", @style = "height: 260px;", @id = "L_content", @name = "content", @placeholder = "详细描述" } })*@
                                        <textarea id="L_content" name="content" required lay-verify="required" placeholder="详细描述" class="layui-textarea fly-editor" style="height: 260px;"></textarea>
                                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="layui-form-item">
                                    <label for="L_vercode" class="layui-form-label">人类验证</label>
                                    <div class="layui-input-inline">
                                        <input type="text" id="L_vercode" name="vercode" required lay-verify="required" placeholder="请回答后面的问题" autocomplete="off" class="layui-input">
                                    </div>
                                    <div class="layui-form-mid">
                                        <span style="color: #c00;">1+1=?</span>
                                    </div>
                                </div>
                                <div class="layui-form-item">
                                    <input type="submit" value="立即发布" class="layui-btn" lay-filter="*" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Scripts/layui.js"></script>
<script>

    layui.config({
        version: "3.0.0"
        , base: "/Scripts/mods/"
    }).extend({
        fly: 'index'
    }).use('fly');
</script>

DiscussProject/Views/Articles/Delete.cshtml
@model DiscussProject.Models.Article

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Like)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Like)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViewNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViewNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DiscussProject/Views/Articles/Detail2.cshtml
@model DiscussProject.Models.Article
@{
    ViewBag.Title = "Detail2";
    Layout = "~/Views/Shared/_ArticleLayout.cshtml";
}
@section showinfo{
    <cite class="layui-hide-xs">@ViewBag.myinfo.Name</cite>
    <img src="@ViewBag.myinfo.Picture">
}

<div class="layui-container">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md8 content detail">
            <div class="fly-panel detail-box">
                <h1>@Model.Title</h1>
                <!-- 发帖人信息 -->
                <div class="detail-about">
                    <a class="fly-avatar" href="../user/home.html">
                        <img src="@Model.Author.Picture" alt="@Model.Author.Name">
                    </a>
                    <div class="fly-detail-user">
                        <a href="../user/home.html" class="fly-link">
                            <cite>@Model.Author.Name</cite>
                        </a>
                        <span>@Model.CreateTime</span>
                    </div>
                </div>
                <!-- 帖子内容 -->
                <div class="detail-body photos">
                    @Model.Content
                </div>
            </div>

            <div class="fly-panel detail-box" id="flyReply">
                <fieldset class="layui-elem-field layui-field-title" style="text-align: center;">
                    <legend>回帖</legend>
                </fieldset>

                <ul class="jieda" id="jieda">
                    @foreach (var item in (IEnumerable<DiscussProject.Models.Comment>)ViewData["comments"])
                    {
                        <li data-id="111" class="jieda-daan">
                            <a name="item-1111111111"></a>
                            <div class="detail-about detail-about-reply">
                                <a class="fly-avatar" href="">
                                    <img src="@item.User.Picture" alt=" ">
                                </a>
                                <div class="fly-detail-user">
                                    <a href="" class="fly-link">
                                        <cite>@item.User.Name</cite>
                                    </a>

                                    <span>(楼主)</span>
                                </div>

                                <div class="detail-hits">
                                    <span>@item.CreateTime</span>
                                </div>
                            </div>
                            <div class="detail-body jieda-body photos">
                                <p>@item.Content</p>
                            </div>
                            <div class="jieda-reply">
                                <span class="jieda-zan zanok" type="zan">
                                    <i class="iconfont icon-zan"></i>
                                    <em>0</em>
                                </span>
                                <span type="reply">
                                    <i class="iconfont icon-svgmoban53"></i>
                                    回复
                                </span>
                                <div class="jieda-admin">
                                    <span type="edit">编辑</span>
                                    <span type="del"><a href="/Comments/Delete2?id=@item.Id&articleId=@Model.Id">删除</a></span>
                                    <span class="jieda-accept" type="accept">采纳</span>
                                </div>
                            </div>
                        </li>
                    }
                </ul>

                <div class="layui-form layui-form-pane">
                    @using (Html.BeginForm("SubmitComment", "Articles"))
                    {
                        <div class="layui-form-item layui-form-text">
                            <a name="comment"></a>

                            <div class="layui-input-block">

                                @Html.TextArea("content", "", new
                                {
                                    id = "L_content",
                                    name = "content",
                               lay_verify = "required",
                                    placeholder = "请输入内容",
                                      @class = "layui-textarea fly-editor",
                                    style = "height: 150px;"
                                })

                                @*<textarea id="L_content" name="content" required lay-verify="required" placeholder="请输入内容"
                                    class="layui-textarea fly-editor" style="height: 150px;"></textarea>*@
                            </div>
                        </div>
                        <div class="layui-form-item">
                            @Html.Hidden("articleId", Model.Id)
                            @*<input type="hidden" name="jid" value="123">*@
                            <button class="layui-btn" id="ab" lay-filter="*" lay-submit>提交回复</button>
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="layui-col-md4">
            <div class="fly-panel" style="padding: 20px 0; text-align: center;">
                <img src="/fly-master/res/images/weixin.jpg" style="max-width: 100%;" alt="layui">
                <p style="position: relative; color: #666;">广州中医药大学</p>
            </div>

        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jquery")
<script>
    $('#ab').click(function () {
        window.location.reload()
    })
</script>

DiscussProject/Views/Articles/Details.cshtml
@model DiscussProject.Models.Article

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Like)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Like)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViewNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViewNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DiscussProject/Views/Articles/Edit2.cshtml
@model DiscussProject.Models.Article

@{
    ViewBag.Title = "Edit2";
    Layout = "~/Views/Shared/_ArticleLayout.cshtml";
}


@using (Html.BeginForm("Edit2","Articles"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model=>model.Id)

    <div class="layui-container fly-marginTop">
        <div class="fly-panel" pad20 style="padding-top: 5px;">
            <!--<div class="fly-none">没有权限</div>-->
            <div class="layui-form layui-form-pane">
                <div class="layui-tab layui-tab-brief" lay-filter="user">
                    <ul class="layui-tab-title">
                        <li class="layui-this">发表新帖<!-- 编辑帖子 --></li>
                    </ul>
                    <div class="layui-form layui-tab-content" id="LAY_ucm" style="padding: 20px 0;">
                        <div class="layui-tab-item layui-show">
                            <form action="" method="post">
                                <div class="layui-row layui-col-space15 layui-form-item">
                                    <div class="layui-col-md3">
                                        <label class="layui-form-label">所在专栏</label>

                                        <div class="layui-unselect layui-form-select">
                                            <div class="layui-input-block">
                                                @*@Html.DropDownList("Category",(SelectList)ViewBag.aaa);*@
                                                @Html.DropDownListFor(model => model.Category, ViewBag.select as SelectList, new { @class = "form-control", @name = "class" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="layui-col-md9">
                                        <label for="L_title" class="layui-form-label">标题</label>


                                        <div class="layui-input-block">
                                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @type = "text", @class = "layui-input", @id = "L_title", @name = "title", @autocomplete = "off" } })
                                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                            <!-- <input type="hidden" name="id" value="{{d.edit.id}}"> -->
                                        </div>
                                    </div>
                                </div>
                                <div class="layui-form-item layui-form-text">
                                    <div class="layui-input-block">
                                        <textarea id="L_content" name="content" required lay-verify="required" placeholder="详细描述" class="layui-textarea fly-editor" style="height: 260px;">@Model.Content</textarea>
                                        @*@Html.TextArea("content",(string)ViewBag.content, new { htmlAttributes = new { @type = "textarea", @class = "layui-textarea fly-editor", @style = "height: 260px;", @id = "L_content", @name = "content", @placeholder = "详细描述" } })*@
                                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="layui-form-item">
                                    <label for="L_vercode" class="layui-form-label">人类验证</label>
                                    <div class="layui-input-inline">
                                        <input type="text" id="L_vercode" name="vercode" required lay-verify="required" placeholder="请回答后面的问题" autocomplete="off" class="layui-input">
                                    </div>
                                    <div class="layui-form-mid">
                                        <span style="color: #c00;">1+1=?</span>
                                    </div>
                                </div>
                                <div class="layui-form-item">
                                    <input type="submit" value="立即发布" class="layui-btn" lay-filter="*" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Scripts/layui.js"></script>
<script>

    layui.config({
        version: "3.0.0"
        , base: "/Scripts/mods/"
    }).extend({
        fly: 'index'
    }).use('fly');
</script>